https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package

# Importing libraries

In [1]:

import numpy as np #for numerical operations.
import pandas as pd #for data manipulation.

# Importing Dataset

In [2]:
dataset = pd.read_csv('weatherAUS.csv') #reading the csv file


In [29]:
dataset.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

In [28]:
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values  # get the needed columns we will make prediction based on that data
Y = dataset.iloc[:,-1].values

In [3]:


print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Brisbane' 11.7 20.8 ... 17.5 18.8 'No']
 ['Brisbane' 11.6 20.9 ... 16.7 20.4 'No']
 ['Brisbane' 10.9 22.4 ... 15.3 22.0 'No']]


In [4]:

print(Y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [5]:


Y = Y.reshape(-1,1)

# Dealing with invalid Data

In [6]:
from sklearn.impute import SimpleImputer #for handling missing data.
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')  #replace the nan value with most frequent value
X = imputer.fit_transform(X)   # Fits the imputer on X and transforms X, filling missing values.
Y = imputer.fit_transform(Y)

In [7]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Brisbane' 11.7 20.8 ... 17.5 18.8 'No']
 ['Brisbane' 11.6 20.9 ... 16.7 20.4 'No']
 ['Brisbane' 10.9 22.4 ... 15.3 22.0 'No']]


In [8]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


# Encoding Dataset

In [9]:
from sklearn.preprocessing import LabelEncoder  #r converting categorical data to numeric
le1 = LabelEncoder()  #  Creates a LabelEncoder instance for encoding categorical features.
X[:,0] = le1.fit_transform(X[:,0])  #Encodes the first feature in X
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])  # Encodes the fifth feature in X
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])  #  Encodes the seventh feature in X
le4 = LabelEncoder() # Creates another LabelEncoder instance.
X[:,7] = le4.fit_transform(X[:,7])  # Encodes the eighth feature in X
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])  # Encodes the target variable Y

In [10]:
print(X)

[[0 13.4 22.9 ... 16.9 21.8 0]
 [0 7.4 25.1 ... 17.2 24.3 0]
 [0 12.9 25.7 ... 21.0 23.2 0]
 ...
 [4 11.7 20.8 ... 17.5 18.8 0]
 [4 11.6 20.9 ... 16.7 20.4 0]
 [4 10.9 22.4 ... 15.3 22.0 0]]


In [11]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [12]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


# Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler  #
sc = StandardScaler()    #  Creates a StandardScaler instance for feature scaling
X = sc.fit_transform(X)   # Fits the scaler on X and transforms X, standardizing the features.

In [14]:
print(X)

[[-1.65691649  0.35432813  0.11094356 ...  0.1889065   0.17416037
  -0.53468267]
 [-1.65691649 -0.63277254  0.43204888 ...  0.23898104  0.55149426
  -0.53468267]
 [-1.65691649  0.27206974  0.51962305 ...  0.87325853  0.38546735
  -0.53468267]
 ...
 [-1.18255313  0.0746496  -0.19556607 ...  0.28905558 -0.2786403
  -0.53468267]
 [-1.18255313  0.05819793 -0.18097037 ...  0.15552347 -0.03714661
  -0.53468267]
 [-1.18255313 -0.05696382  0.03796507 ... -0.07815771  0.20434708
  -0.53468267]]


# Splitting Dataset into Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split  # for spliting the data
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [17]:


print(X_train)

[[ 0.83349116 -0.10631885 -0.37071443 ... -0.26176436 -0.38429379
  -0.53468267]
 [ 1.5450362   1.2591704   0.3152833  ...  0.75641794 -0.03714661
   1.87026821]
 [-0.11523556  0.14045632  0.14013495 ...  0.20559801  0.20434708
  -0.53468267]
 ...
 [ 1.66362704  1.48949389  0.68017571 ...  1.19039728  0.73261453
  -0.53468267]
 [ 1.66362704  0.12400464 -0.79398962 ... -0.17830679 -0.64088083
  -0.53468267]
 [-0.58959893 -0.20502892 -0.92535089 ... -0.66236067 -1.01821472
  -0.53468267]]


In [18]:


print(Y_train)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


# Training Model

In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(random_state=0)

In [20]:
classifier.score(X_train,Y_train)  # Evaluates the model’s performance on the training data.

0.9998992820247191

In [21]:

y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:


print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [23]:


print(Y_test)

['Yes' 'No' 'No' ... 'No' 'No' 'No']


In [24]:
c

In [25]:

df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])


In [26]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                    No                No
2                    No                No
3                    No                No
4                   Yes               Yes
...                 ...               ...
17371                No                No
17372                No                No
17373                No                No
17374                No                No
17375                No                No

[17376 rows x 2 columns]


# Calculating Accuracy

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8454765193370166

# Save the Model

In [30]:
import joblib

# Save the trained model to a file
joblib.dump(classifier, 'rain_prediction_model.pkl')


['rain_prediction_model.pkl']

# Load the Model and Test It

In [36]:
import numpy as np
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Load the saved model
classifier = joblib.load('rain_prediction_model.pkl')

# Load the dataset for preprocessing steps
dataset = pd.read_csv('weatherAUS.csv')
X = dataset.iloc[:, [1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]].values
Y = dataset.iloc[:, -1].values

# Impute missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X = imputer.fit_transform(X)

# Label encode categorical variables
le1 = LabelEncoder()
X[:, 0] = le1.fit_transform(X[:, 0])

le2 = LabelEncoder()
X[:, 4] = le2.fit_transform(X[:, 4])

le3 = LabelEncoder()
X[:, 6] = le3.fit_transform(X[:, 6])

le4 = LabelEncoder()
X[:, 7] = le4.fit_transform(X[:, 7])

le5 = LabelEncoder()
X[:, -1] = le5.fit_transform(X[:, -1])

le6 = LabelEncoder()
Y = le6.fit_transform(Y)

# Feature scaling
sc = StandardScaler()
X = sc.fit_transform(X)

# Save preprocessing objects
joblib.dump(imputer, 'imputer.pkl')
joblib.dump(le1, 'le1.pkl')
joblib.dump(le2, 'le2.pkl')
joblib.dump(le3, 'le3.pkl')
joblib.dump(le4, 'le4.pkl')
joblib.dump(le5, 'le5.pkl')
joblib.dump(le6, 'le6.pkl')
joblib.dump(sc, 'sc.pkl')

# Load preprocessing objects for testing
imputer = joblib.load('imputer.pkl')
le1 = joblib.load('le1.pkl')
le2 = joblib.load('le2.pkl')
le3 = joblib.load('le3.pkl')
le4 = joblib.load('le4.pkl')
le5 = joblib.load('le5.pkl')
le6 = joblib.load('le6.pkl')
sc = joblib.load('sc.pkl')

# Prepare sample input (ensure it has all 19 features)
sample_data = np.array([[0, 13.4, 22.9, 0.6, 44.0, 0.0, 71.0, 22.0, 1007.7, 8.0, 16.9, 21.8, 0, 0, 0, 0, 0, 0, 0]])

# Apply imputation to the sample data
sample_data = imputer.transform(sample_data)

# Handle Label Encoding with consistent categories
def safe_transform(encoder, data):
    # Convert all unknown labels to a known value or handle accordingly
    known_values = encoder.classes_
    transformed_data = np.array([val if val in known_values else known_values[0] for val in data])
    return encoder.transform(transformed_data)

# Label encode sample data
sample_data[:, 0] = safe_transform(le1, sample_data[:, 0])
sample_data[:, 4] = safe_transform(le2, sample_data[:, 4])
sample_data[:, 6] = safe_transform(le3, sample_data[:, 6])
sample_data[:, 7] = safe_transform(le4, sample_data[:, 7])

# Feature scaling
sample_data = sc.transform(sample_data)

# Predict
prediction = classifier.predict(sample_data)

# Ensure prediction is integer type
prediction = prediction.astype(int)

# Handle decoding errors
def safe_inverse_transform(encoder, data):
    try:
        return encoder.inverse_transform(data)
    except ValueError as e:
        print(f"Error during inverse transformation: {e}")
        return [np.nan] * len(data)

prediction_decoded = safe_inverse_transform(le6, prediction)

print(f'Prediction for the sample data: {prediction_decoded[0]}')


Prediction for the sample data: Yes
